name: Tag on Merge to Main

on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Get latest tag
        id: get_latest_tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "0")
          echo "Latest tag: $latest_tag"
          echo "::set-output name=tag::$latest_tag"

      - name: Calculate new tag
        id: calculate_new_tag
        run: |
          latest_tag=${{ steps.get_latest_tag.outputs.tag }}
          echo "Latest tag: $latest_tag"
          if [ "$latest_tag" = "0" ]; then
            new_tag="1"
          else
            new_tag=$((latest_tag + 1))
          fi
          echo "New tag: $new_tag"
          echo "::set-output name=new_tag::$new_tag"

      - name: Create new tag
        run: |
          new_tag=${{ steps.calculate_new_tag.outputs.new_tag }}
          git tag $new_tag
          git push origin $new_tag
