name: Tag on Merge

on:
  push:
    branches:
      - '**'

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Get latest tag
      id: get_latest_tag
      run: |
        git fetch --tags
        echo $(git describe --tags)
        latest_tag=$(git describe --tags 2>/dev/null || echo "0")
        echo "Latest tag: $latest_tag"
        echo "::set-output name=tag::$latest_tag"
      
    - name: Calculate new tag
      id: calculate_tag
      run: |
        latest_tag=${{ steps.get_latest_tag.outputs.tag }}
        if [[ "$latest_tag" == "0" ]]; then
          new_tag="1"
        else
          new_tag=$((latest_tag + 1))
        fi
        echo "New tag: $new_tag"
        echo "::set-output name=new_tag::$new_tag"
      
    - name: Create and push new tag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        new_tag=${{ steps.calculate_tag.outputs.new_tag }}
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git tag $new_tag
        git push origin $new_tag
